Repository renato-dl/ESRMS-GroupG, pull requests merged in 2019-11, with the labels that each got.

#100 Added db migrations and seeders
  .env.example
  README.md
  db-queries/00-init-dababase.sql
  db-queries/01-update-students-grades-and-to-timestamp.sql
  db-queries/02-insert-mock-data-for-parents.sql
  db-queries/03-insert-mock-data-for-teachers-classes-students-subjects-grades.sql
  db-queries/04-table-topics-and-mock-data.sql
  db-queries/05-change-topics-table-add-elements.sql
  knexfile.js
  package-lock.json
  package.json
  src/database/migrations/20191114092141_CreateTeachers.js
  src/database/migrations/20191114092241_CreateClasses.js
  src/database/migrations/20191114092341_CreateParents.js
  src/database/migrations/20191114092541_CreateStudents.js
  src/database/migrations/20191114092641_CreateSubjects.js
  src/database/migrations/20191114093327_CreateGrades.js
  src/database/migrations/20191114094412_CreateTeacherSubjectClassRelation.js
  src/database/migrations/20191114094412_CreateTopics.js
  src/database/migrations/20191114161033_Xhoiker.js
  src/database/seeds/1.ParentsSeed.js
  src/database/seeds/2.TeachersSeed.js
  src/database/seeds/3.ClassesSeed.js
  src/database/seeds/4.StudentsSeed.js
  src/database/seeds/5.SubjectsSeed.js
  src/database/seeds/6.GradesSeed.js
  src/database/seeds/7.TeacherSubjectClassRelationSeed.js
  src/database/seeds/8.TopicsSeed.js
  src/database/seeds/dasdasd.js
Labels: BACK END

#102 Story2/issue49
  src/controllers/teacherController.js
  src/database/models/topic.js
Labels: BACK END, TASK

#105 Story2/issue#50
  __tests__/teacher.test.js
  src/database/models/topic.js
Labels: BACK END, TASK

#128 Add files via upload
  UC&Personas/Use cases/STORY2.md
Labels: TASK

#207 Issue#152
  __tests__/parent.test.js
  src/database/migrations/20191122095157_UpdateGrades.js
  src/database/models/grade.js
  src/database/seeds/6.GradesSeed.js
Labels: BACK END

#276 Fix get students data
  src/controllers/adminController.js
  src/database/models/student.js
  src/database/models/user.js
Labels: BACK END, STORY 5
